<h1>Add New Contact</h1>

<?php

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Contact Name');

$phone = $form->get('phone');
$phone->setAttribute('class', 'form-control');
$phone->setAttribute('placeholder', 'Contact Phone Number');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('contact', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($phone) ?>
    <?= $this->formElement($phone) ?>
    <?= $this->formElementErrors()->render($phone, ['class' => 'help-block']) ?>
</div>

<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
