<?php

$title = 'Delete album';
$url   = $this->url('contact', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($contact->name) ?>" -
    "<?= $this->escapeHtml($contact->phone) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $contact->id ?>" />
        <input type="submit" class="btn btn-danger" name="delete" value="Yes" />
        <input type="submit" class="btn btn-success" name="delete" value="No" />
    </div>
</form>